### ISSUE TITLE
Не запускается tars dev -l

### ISSUE THREAD

**Issue by rtxrulez** [tars/tars-cli#10]
[BS] Access URLs:
 --------------------------------------------------
       Local: http://localhost:3004/index.html
    External: http://192.168.10.100:3004/index.html
 --------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.10.100:3001
 --------------------------------------------------
[BS] Serving files from: dev

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)

Вот что выводит при попытке выполнить tars dev -l . Настройки почти все стандартные. только препроцессор поменял на less

версия 
nodejs -v
v0.10.37

**Comment by artem-malko** [comment]
@rtxrulez А какая ОС?

**Comment by rtxrulez** [comment]
kubuntu 14.04

**Comment by rtxrulez** [comment]
@artem-malko Если нужна какая то помощь то пишите, буду рад помочь.

**Comment by rtxrulez** [comment]
Только что установил tars-cli c нуля. И в tars-config.js поменял браузер.
Было:
        browser: 'google chrome',
Стало:
        browser: 'chromium-browser',
И tars dev -l запустился без ошибок. Ура!

**Comment by artem-malko** [comment]
@rtxrulez значит проблема была именно в том, что такого браузера не было на машине?

**Comment by artem-malko** [comment]
@rtxrulez спасибо, помогли вскрыть недоработку одну) По умолчанию tars должен открывать браузер, который стоит по дефолту в системе. Сегодня же выпущу хотфикс. Спасибо. Ишью закрываю.

**Comment by artem-malko** [comment]
@rtxrulez хотфикс на бою. Теперь по умолчанию дефолтный браузер будет.
