### ISSUE TITLE
Won't work on Windows 10

### ISSUE THREAD

**Issue by rucomcode** [tars/tars-cli#100]
```
|[ TARS ]: Please wait for a moment, while I'm preparing builder for working...

gulp[12644]: src\node_contextify.cc:633: Assertion `args[1]->IsString()' failed.
 1: 00007FF749AF0EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF749ACA296 node::MakeCallback+4518
 3: 00007FF749ACA34F node::MakeCallback+4703
 4: 00007FF749A9D5E8 node::DecodeWrite+12952
 5: 00007FF74A2FADD2 v8::internal::OptimizingCompileDispatcher::Unblock+60562
 6: 00007FF74A2FBF58 v8::internal::OptimizingCompileDispatcher::Unblock+65048
 7: 00007FF74A2FB28D v8::internal::OptimizingCompileDispatcher::Unblock+61773
 8: 00007FF74A2FB1AB v8::internal::OptimizingCompileDispatcher::Unblock+61547
 9: 000000B7634DC5C1

```
node 10.15.1
nvm 6.4.1

**Comment by rucomcode** [comment]
> Have you tried run tars-cli on other NodeJS versions?

Works with 8.15.0
I find better solution – use WSL

**Comment by Tibon4ik** [comment]
Same problem.
node 10.13.0
npm 6.4.1

|[ TARS ]: You can change all options in tars-config.js

|[ TARS ]: Please, wait for a moment, while magic is happening...

nothing more

**Comment by TheRagnar** [comment]
> Similar problem.
> node 10.13.0
> npm 6.4.1
> 
> |[ TARS ]: You can change all options in tars-config.js
> 
> |[ TARS ]: Please, wait for a moment, while magic is happening...
> 
> nothing more. Infinite init

exactly the same problem

**Comment by artem-malko** [comment]
What about https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux ?

**Comment by artem-malko** [comment]
@TheRagnar @Tibon4ik up?)

**Comment by artem-malko** [comment]
@Tibon4ik @TheRagnar @bukhalo @rucomcode 

Update troubleshooting https://github.com/tars/tars-cli/blob/master/docs/en/troubleshooting.md#i-have-started-tars-command-on-windows-in-console-please-wait-for-a-moment-while-im-preparing-builder-for-working-and-nonthing-more-is-happen

Обновил troubleshooting https://github.com/tars/tars-cli/blob/master/docs/ru/troubleshooting.md#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D0%BB-%D0%BB%D1%8E%D0%B1%D1%83%D1%8E-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-tars-%D0%BD%D0%B0-windows-%D0%B2-%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D0%B8-please-wait-for-a-moment-while-im-preparing-builder-for-working-%D0%B8-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B5-%D0%BD%D0%B8%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82

Если есть проблемы с запуском на windows — прямиком сюда надо идти за решением.
