### ISSUE TITLE
Please, wait for a moment, while magic is happening...

### ISSUE THREAD

**Issue by TheRagnar** [tars/tars-cli#101]
2 раза переустанавливал винду, винда чистая. Устанавливаю node, устанавливаю tars-cli , и при tarts init http://joxi.ru/52aVyaDC46R6DA  вот это висит вечно, причем через ctrl+c консоль не реагирует. 
node -v :
v10.15.2
npm -v :
6.8.0

**Comment by artem-malko** [comment]
What about https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux ? Or NodeJS 8.5

**Comment by artem-malko** [comment]
Обновил пакеты. по идее должно пропасть.

**Comment by denistrator** [comment]
@artem-malko у меня такая же проблема на Windows 10 (1903)
tars 1.11.1
node 10.16.1
npm 6.9.0

**Comment by artem-malko** [comment]
@denistrator рекомендую использовать wsl https://docs.microsoft.com/ru-ru/windows/wsl/install-win10
Встроенный терминал прям не очень(
Напишите, помогло или нет?)

**Comment by denistrator** [comment]
да, на wsl работает. спасибо

**Comment by artem-malko** [comment]
Круто!)

**Comment by artem-malko** [comment]
Update troubleshooting https://github.com/tars/tars-cli/blob/master/docs/en/troubleshooting.md#i-have-started-tars-command-on-windows-in-console-please-wait-for-a-moment-while-im-preparing-builder-for-working-and-nonthing-more-is-happen

Обновил troubleshooting https://github.com/tars/tars-cli/blob/master/docs/ru/troubleshooting.md#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D0%BB-%D0%BB%D1%8E%D0%B1%D1%83%D1%8E-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-tars-%D0%BD%D0%B0-windows-%D0%B2-%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D0%B8-please-wait-for-a-moment-while-im-preparing-builder-for-working-%D0%B8-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B5-%D0%BD%D0%B8%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82

Если есть проблемы с запуском на windows — прямиком сюда надо идти за решением.
