### ISSUE TITLE
 .babelrc must be a boolean, or undefined

### ISSUE THREAD

**Issue by epicfail169** [tars/tars-cli#102]
Предыстория: недавно пришлось переустановить винду со всеми вытекающими.
Перестал работать один из проектов на tars, ругается на  .babelrc must be a boolean, or undefined. Другие проекты на tars запусаются и всё работает. Файлы .babelrc идентичны у них.

Удивительно то что данный проект работает без проблем на другом компе... 

[13:29:01] gulp-notify: [TARS notification]
An error occurred while processing js-files.
Look in the console for details.

Error details:

.babelrc must be a boolean, or undefined

**Comment by epicfail169** [comment]
Решил проблему инициализацией пустого проекта и переноса из него файла .babelrc, зависимостей и js тасков.

**Comment by artem-malko** [comment]
Интересно, что было)

**Comment by epicfail169** [comment]
Сам не понимаю что это было, учитывая что другие проекты работают со старым .babelrc и старыми js тасками

**Comment by artem-malko** [comment]
Если у кого-то возникла такая проблема, нужно просто выполнить в папке с проектом:
```
tars update-project
```
Проект будет обновлен. Все старые файлы проекта будут забекаплены.
