### ISSUE TITLE
css && JS minify

### ISSUE THREAD

**Issue by veremey** [tars/tars-cli#103]
Здравствуй, @artem-malko  
Не могу найти функцию, при которой минифицируются css && JS . 
Не верю что такой не предусмотренно. 
Пробовал `tars build -m ` - не помогло 
Спасибо

**Comment by artem-malko** [comment]
@veremey была проблема такая. https://github.com/tars/tars-cli/releases/tag/1.10.3 тут пофикшено должно быть. Если не сработает, то предлагаю флаг --min использовать. Если -m не работает, прошу отписаться)

**Comment by veremey** [comment]
@artem-malko  Спасибо, за разъяснения. 
`tars build -m` - работает. 
В созданой папке `builds` действительно есть два файла .css` и `.min.css` скрипты сжаты. 
Спасибо

**Comment by artem-malko** [comment]
Прекрасно, закрываю тикет
