### ISSUE TITLE
Erro on init ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by aleksandr-guryanov** [tars/tars-cli#108]
```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/aleksandr/markup/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/aleksandr/markup/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/aleksandr/markup/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
```
macOS Catalina
TARS-CLI version: "1.11.1"
TARS version in current project: "1.13.1"
Gulp 
CLI version: 2.2.0
Local version: 3.9.1
node version: 10.17.0, 12.13.1, 13.2.0, 8.16.2, 6.17.1  (через nvm)

Пробовал с разными версиями node и gulp, обновлял natives и graceful-fs не помогает. Просто не заводиться. Gulp отдельно работает и 3 и 4 версия без проблем. В чем может быть проблема ? Тарс выдает ошибки и все при инициализации. Гугл и Стак с их решениями не помогли.

**Comment by artem-malko** [comment]
Странно, по идее 10 или 11 нода должны были помочь. Предлагаю еще раз начисто попробовать установить на 10 или 11 ноде.

**Comment by selim13** [comment]
Это проблема несовместимости gulp 3 и node 12.
https://github.com/gulpjs/gulp/issues/2324

Даунгрейд ноды до v11.15.0 точно помогает.

**Comment by aleksandr-guryanov** [comment]
> Это проблема несовместимости gulp 3 и node 12.
> [gulpjs/gulp#2324](https://github.com/gulpjs/gulp/issues/2324)
> 
> Даунгрейд ноды до v11.15.0 точно помогает.

Через NVM пробовал разные версии node начиная с 8 версии, не завелось. В том числе и 11 версия была.

**Comment by artem-malko** [comment]
@aleksandr-guryanov может проблема с nvm какая-то? Попробуй n.

**Comment by TIIGRUS** [comment]
Такая же байда с недавних пор, когда переустановил ноду началось.

**Comment by TIIGRUS** [comment]
Обновление до последней версии node вызывает ошибку. На 11.15.0 стартует, правда я сделал чистку папки node в C:\Users\user\AppData\Roaming/npm

**Comment by artem-malko** [comment]
Попробую на новогодних праздниках перейти на 4 gulp

**Comment by artem-malko** [comment]
Уже в мастере) Сегодня будет релиз.

**Comment by artem-malko** [comment]
@selim13 @TIIGRUS @aleksandr-guryanov ну чтож, 1.12.2 tars-cli) Всем обновляться!)
Обновить проект можно автоматом tars update-project в папке с проектом.

**Comment by TIIGRUS** [comment]
Супер!) Накатим.

**Comment by artem-malko** [comment]
@TIIGRUS tars upgrade && tars update-project =)
