### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by cainbyrne** [tars/tars-cli#113]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at https://source-security.co.uk/25374701-b09b-4642-b01f-e1bbb0d91978/ so you can see if anything needs handled.  Feel free to re-run the security scanning anytime you like, it’s free for open source.

Best of luck,

Cain

**Comment by artem-malko** [comment]
@cainbyrne thx for scanning) Yes, we know about security vulnerabilities. But we have so many deps and it will be really hard to update them all. Many of deps are not maintained. 

All security vulnerabilities are not so critical, actually. And the main problem is old lodash.
