### ISSUE TITLE
Проблемы запуска

### ISSUE THREAD

**Issue by veremey** [tars/tars-cli#114]
При запуске с командной строки `tars init` инициализация проходит без проблем.
Делаю `tars dev` выкидывает ошибку. 
$ node -v == v10.16.0
$ npm -v == 6.14.5 
windows 10 

![image](https://user-images.githubusercontent.com/6988442/85145999-122b9880-b256-11ea-90ab-7e5736dba91b.png)

**Comment by artem-malko** [comment]
@veremey выглядит так, что ОС запрещает просто прослушивать порт приложению. Можно попробовать запускать сборку от админа, но я бы рекомендовал разобраться именно с правами сначала.

**Comment by veremey** [comment]
@artem-malko   
Обновления tars-cli не помогли. 
Помогло: Установка node 9. 
Удобная утилита для этого - [nvm для windows](https://github.com/coreybutler/nvm-windows/releases)

**Comment by artem-malko** [comment]
@veremey проблема точно не в node) Были проблемы с правами на открытие порта
