### ISSUE TITLE
Some problems with launching tars-cli

### ISSUE THREAD

**Issue by Ankook** [tars/tars-cli#124]
The end of installation is a problem.
Problems starts after this string: 
reify:rxjs: timing reifyNode:node_modules/tars-cli/node_modules/inquirer/node_modules/rxjs Completed in 18948ms
Problem 
![Screenshot 2021-06-14 at 04 59 40](https://user-images.githubusercontent.com/52046510/121830315-70565480-cccd-11eb-83f2-65520e6fe675.png)
![Screenshot 2021-06-14 at 04 59 43](https://user-images.githubusercontent.com/52046510/121830318-72201800-cccd-11eb-9a2f-155078947075.png)
![Screenshot 2021-06-14 at 04 59 48](https://user-images.githubusercontent.com/52046510/121830320-72b8ae80-cccd-11eb-838f-6b5bff81b08a.png)
![Screenshot 2021-06-14 at 04 59 50](https://user-images.githubusercontent.com/52046510/121830323-73514500-cccd-11eb-86b6-5b61e430c1a1.png)
![Screenshot 2021-06-14 at 04 59 53](https://user-images.githubusercontent.com/52046510/121830325-73e9db80-cccd-11eb-969c-d94df95fb2a4.png)
![Screenshot 2021-06-14 at 04 59 58](https://user-images.githubusercontent.com/52046510/121830327-74827200-cccd-11eb-9467-dbb2b5166df9.png)

**Comment by Ankook** [comment]
I use Mac Os Big Sur version 11.4

**Comment by artem-malko** [comment]
Hi!

You can try to use older version of NodeJS. You can use package [n](https://www.npmjs.com/package/n) to switch versions.

**Comment by Ankook** [comment]
Thank you, i will try it

**Comment by Ankook** [comment]
Thank you!
I install node -v 10.16.0 and its really working.
Issue closed
