### ISSUE TITLE
проблема, постоянно просит обновить TARS

### ISSUE THREAD

**Issue by vaeum** [tars/tars-cli#18]
Здравствуйте, установил TARS-CLI и после инициализации проекта и ответа на вопросы, 
возникает ошибка,  которая просит обновить TARS.

такст из терминала https://kobra.io/#/e/-K0636RTruD_hiyoTDvL

OS: Mac OSX, El Capitan
node v4.1.1
npm v3.3.5
tars  v1.2.3

**Comment by artem-malko** [comment]
Проблема в npm@3. Тарс пока не работает с npm третьей версии
