### ISSUE TITLE
MSBUILD : error MSB3428

### ISSUE THREAD

**Issue by nikitakiselev** [tars/tars-cli#26]
При установке ```npm i -g tars-cli```

MSBUILD : error MSB3428: Загрузка компонента Visual C++ "VCBuild.exe" невозможна. Способы решения проблемы: 1) установка .NET Framework 2.0 SDK, 2) установка Microsoft Visual Studio 2005 или 3) указание адреса компонента в системном пути, если компонент установлен в другом месте.  [C:\Users\admin\AppData\Roaming\npm\node_modules\tars-cli\node_modules\bufferutil\build\binding.sln]

**Comment by nikitakiselev** [comment]
Установил  .NET Framework 2.0 SDK, но проблема не ушла

**Comment by vaeum** [comment]
а попробуйте Microsoft Visual Studio 2005 установить

**Comment by artem-malko** [comment]
@nikitakiselev согласен с установкой Microsoft Visual Studio 2005 + подскажите, какой пакет выдал такую ошибку?

**Comment by nikitakiselev** [comment]
Да, всё таки пришлось установить microsoft visual studio 2012. Ошибку на сколько я понял выдавал пакет node-gyp

**Comment by artem-malko** [comment]
@nikitakiselev node-gyp занимается компиляцей пакетов. Подскажите, при компиляции какого пакета происходила ошибка?
И еще момент, та ошибка не позволяла установить TARS-CLI или устанвока проходила успешно?
