### ISSUE TITLE
Как перенести свой проект на другой комп?

### ISSUE THREAD

**Issue by alexd73** [tars/tars-cli#29]
Привет!
Возможно мой вопрос слишком простой, но я новичок в Node.js и могу что-то не знать)

в общем делаю верстку, спушил ее на битбакет, думаю на новом компе раскатаю. Ок. дома клонирую репозиторий, запускаю 
```
npm i -g tars-cli
npm install
gulp update-deps
# И получаю для каждого модуля

module.js:338
    throw err;
    ^
Error: Cannot find module 'gulp-util'
```
само собой помогает
```
npm install --save-dev 
```
но так для каждого модуля, а их много. Как сделать это одной командой?

**Comment by alexd73** [comment]
upd: Похоже node был не той версии, когда я tars-cli ставил. Сейчас, ставлю заново. установка идет гораздо дольше. О результатах отпишусь.

**Comment by alexd73** [comment]
Все заработало. Из-за невнимательности все проблемы :(

**Comment by artem-malko** [comment]
@alexd73 Бывает)
Но смотри, нужно просто поставить tars-cli глобально. При клоинировании проекта к себе на комп, в папке с проектом нужн овыполнить npm i, чтобы gulp локально установился + твои модули из package.json Не нужно ставить зависимости TARS самому.

**Comment by alexd73** [comment]
Понял, а свои модули все же прописывать в package.json или user-package.json?

**Comment by artem-malko** [comment]
@alexd73 если проект уже заиничен, то в локальном package.json, если инит проекта делается с кастомным TARS, то в user-package.json тут подробнее: https://github.com/tars/tars/blob/master/docs/ru/tasks-workflow.md
