### ISSUE TITLE
Произвольный шаблон модуля

### ISSUE THREAD

**Issue by ilyoff** [tars/tars-cli#31]
Привет. Есть ли возможность создавать кастомный шаблон модуля, например, для модуля в ангуляре: 
```
_template
-- _.template.module.js
-- _template.ctrl.js
--_template.directive.js
```

...и так далее. Было бы круто иметь такую фичу.

**Comment by artem-malko** [comment]
@ilyoff подойдет ли создание модуля, на основе модуля _template? То есть вы сами меняете _template так, как вам удобно, потом tars add-module new -t создаст копию _template, переименовав файлы по имени нового модуля?

**Comment by ilyoff** [comment]
@artem-malko да, вполне подойдет, я думаю
