### ISSUE TITLE
Random Browsersync port on init

### ISSUE THREAD

**Issue by Grawl** [tars/tars-cli#35]
I am developing a lot of project at the same time and trying to set a random port between 3000 and 9000 for each web server started on my machine to avoid their conflicts and let my browser to remember each web app separately.

So I think that will be good to add ability to set a random port for Browsersync on `init` command.

**Comment by artem-malko** [comment]
@Grawl browsersync will start on the first free port by default. Why should TARS override this?

**Comment by Grawl** [comment]
I am talking about `browserSyncConfig.port` in `tars-config.js`.

**Comment by artem-malko** [comment]
@Grawl I understood. But, as I know, browsersync will use another port, if port from tars-config already in use.

**Comment by Grawl** [comment]
Yep. But I don't want to have web app with mutable port.

**Comment by artem-malko** [comment]
@Grawl would you like to set unique port for each app, right? So, if port will be set by random on init it will be equal to current browsersync behavior.
Actually, random can set port, which is already in use, so port could be mutable in that case.
So, there is only one solution — you have to set port by yourself. Actually, I can add port setting from env var. Will it be helpful?

**Comment by Grawl** [comment]
Random from 3000 to 9000 is more stable than defined from 3000 to 3010 (most apps doing it that way) so I prefer just to close my eyes and print four random digits by myself each time I set up new web app.

> add port setting from env var

What it will return? *Know nothing about.*

**Comment by artem-malko** [comment]
Manual control for port is much more reliable and clear way.
There is some info about env vars: http://stackoverflow.com/questions/22312671/node-js-setting-environment-variables

**Comment by Grawl** [comment]
Got it. Okay, better to set it manually. Will be good to set it interactive on init rather than only in config.

**Comment by artem-malko** [comment]
Ok, I'll create issue to set port in interactive mode and set port from env var.

**Comment by Grawl** [comment]
Thank you.

**Comment by artem-malko** [comment]
Resolved by https://github.com/tars/tars/issues/178
