### ISSUE TITLE
Не работает после установки

### ISSUE THREAD

**Issue by jt3k** [tars/tars-cli#36]
Установил тарс-цли

сделал тарс инит

выбрал стилус джейд и несколько ещё опций
![](https://i.imgur.com/eeaHIJD.png)

установилось ок.

пишу npm i

всё ок

затем делаю gulp dev 

и вижу ошибку ![](https://i.imgur.com/QvC42Ql.png)

ок думаю, мож одну зависимость не установили.

ставлю автопрефиксер.,, перепроверяю ещё раз  npm i сделано ли ? -- сделано
затем пишу гулп. 
![](https://i.imgur.com/Ih9FkPk.png)

дальше не разбирался. чините.

**Comment by artem-malko** [comment]
@jt3k использовать gulp вообще не нужно. Согласен, возможно это запутывает в доке (это я исправлю), что есть gulp dev и tars dev. gulp dev испольузется, если нет CLI. Я как мог старался это отобразить в документации. Более того, после инита TARS не нужно выполнять npm i, он выполняется за вас. 
Чтобы начать работу нужно использовать tars:
* tars dev
* tars build
* ...
В доке TARS-CLI сказано, что это обертка над TARS. А в README.md сказано, что использовать нужно только CLI, а не запуск команд через gulp.
В ближайшее время я поправлю доку, уберу вообще куда-нить подальше доку, где вызыватются команды от gulp. 
Запустите tars dev, все ли корректно отработало?

**Comment by artem-malko** [comment]
@jt3k более того, в консоли вас предупреждают, что вы не должны использовать gulp для запуска тасков и нужно из запускать из CLI.

**Comment by jt3k** [comment]
@artem-malko о! Спс сработало! 

в консоли много всего пишут. но я не увидел там 'tars dev'

да и в tars -h ничего про dev не сказано

![](https://i.imgur.com/hDoTd10.png)

спс за подсказку!
