### ISSUE TITLE
Автоматическая генерация блока в модуле

### ISSUE THREAD

**Issue by gearmobile** [tars/tars-cli#40]
При создании нового модуля по команде tars add-module (вариант basic) было бы хорошо так:

- в jade-миксине автоматом прописывается блок (самого общего типа) с именем класса (по имени модуля);
- в стилях добавляется имя класса (по имени модуля) с каким-то одним общим, ничего не значащим правилом.

Иначе приходится вручную каждый раз создавать блок (любого типа) в миксине jade - дополнительная, никому не нужная работа, как мне кажется.

Если не создать блок вручную в миксине jade и подключить такой модуль в шаблон, то TARS выдает ошибку, которая (как мне кажется) слишком **неявно** указывает на суть проблемы.

**Comment by artem-malko** [comment]
In version-1.7.0

**Comment by artem-malko** [comment]
В стилях ничего добавлять не будем, так как каждому тут может потребоваться свое.
