### ISSUE TITLE
Tars init trows the error

### ISSUE THREAD

**Issue by boonya** [tars/tars-cli#46]
> $ tars init
> 🅃 🄰 🅁 🅂 : Initialization has been started!
> 
> 🅃 🄰 🅁 🅂 : I'll be inited in "/Users/boonya/Documents/miks.org.ua/miks-2016.2"
> 🅃 🄰 🅁 🅂 : TARS source will be downloaded from "https://github.com/tars/tars/archive/master.zip"
> 🅃 🄰 🅁 🅂 : You can specify source url by using flag "--source" or "-s"
> 🅃 🄰 🅁 🅂 : Example: "tars init -s http://url.to.zip.with.tars"
> 🅃 🄰 🅁 🅂 : Run command "tars init --help" for more info.
> 
> 🅃 🄰 🅁 🅂 : I'm going to install "gulp" localy and create local package.json
> 🅃 🄰 🅁 🅂 : You can modify package.json by using command "npm init" or manually.
> 🅃 🄰 🅁 🅂 : Please, answer some questions:
> 
> ? What preprocessor for CSS do you want to use? Less
> ? What templater for HTML do you want to use? Handlebars
> ? What workflow for JavaScript processing do you want to use? Modular (Webpack will be used to resolve requires/imports between JavaScript-files)
> ? Would you like to check your JavaScript with ESLint? Yes
> ? Would you like to use ES6 (ES.Next) syntax? No
> ? What dpi of raster-images are you going to use? Available multiple choice. 96, 384
> ? Would you like to use notify in OS? Yes
> ? Enter static directory name static
> ? Enter images directory name img
> 🅃 🄰 🅁 🅂 : You can change all options by useing command "tars re-init".
> 🅃 🄰 🅁 🅂 : Or you can change it manually in tars-config.js
> 
> 🅃 🄰 🅁 🅂 : Please, wait for a moment, while magic is happening...
> 🅃 🄰 🅁 🅂 : TARS version is: 1.7.0
> 🅃 🄰 🅁 🅂 : Local package.json has been created
> 🅃 🄰 🅁 🅂 : Local gulp and other dependencies has been installed
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn /Users/boonya/.npm/lib/node_modules/tars-cli/node_modules/.bin/gulp ENOENT
>     at exports._errnoException (util.js:890:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
>     at onErrorNT (internal/child_process.js:348:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Tars-cli version: "1.7.2"**
**Mac OS 10.11.4**

**Comment by boonya** [comment]
I dunno why, but I've removed all my global npm packages, reintalled tars and it works.

**Comment by artem-malko** [comment]
@boonya it is because you have changed the to global packages.
Is there any errors in console about tunnel mode? What does it mean, "tunneling is not working"?

**Comment by artem-malko** [comment]
@boonya is that issue still valid for you?

**Comment by boonya** [comment]
@artem-malko sorry for delay. I think that was a problem about my firewall (I mean tunnel mode). You can close this issue if you need.
Thanks for great job.
