### ISSUE TITLE
Template files in the custom component folder

### ISSUE THREAD

**Issue by c01nd01r** [tars/tars-cli#58]
During the initialization of the project and setting a custom directory for the components, in the markup folder is created default folder "components" with example templates.
Node v6.2.1
npm v3.9.3
TARS-CLI version: "1.8.4"
TARS version in current project: "1.8.1"
win10 / macosx 10.11

from tars-config.js:
```javascript
    "fs": {
        "staticFolderName": "static",
        "imagesFolderName": "img",
        "componentsFolderName": "blocks"
    }
```

![2016-06-28 9 49 10](https://cloud.githubusercontent.com/assets/3511312/16407165/f0d66e12-3d1a-11e6-9fcf-e22e2d7c2c16.png)
![2016-06-28 10 24 17](https://cloud.githubusercontent.com/assets/3511312/16407166/f0d7b24a-3d1a-11e6-9d8f-e348a75aefad.png)

**Comment by artem-malko** [comment]
@c01nd01r thank you for issue)
