### ISSUE TITLE
Не находит файл в "node_modules/...".

### ISSUE THREAD

**Issue by lxndrrl** [tars/tars-cli#60]
Здравствуйте! 

Пытаюсь подключить файл путём: ```@import` "bootstrap/less/bootstrap.less";``` - не видит.
А так: ```@import "/usr/local/lib/node_modules/bootstrap/less/bootstrap.less";``` - видит.

Подобная история и с JS при ```require('myPath');``` когда необходимо подключить например: ```/usr/local/lib/node_modules/bootstrap/js/tooltip.js```.

**Comment by artem-malko** [comment]
@lxndrrl вы установили bootstrap глобально. NodeJS не умеет рекваирить пакеты, которые установлены глобально.
