### ISSUE TITLE
Doesn't work custom-flags in windows 10 default terminal 

### ISSUE THREAD

**Issue by Lehakos** [tars/tars-cli#68]
Собственно вся суть в заголовке. В windows 10 если запустить `tars dev -l --custom-flags '--custom'` в стандартном терминале, попытка обратиться к флагу через `tars.flags.custom` будет возвращать `undefined`.

**Comment by artem-malko** [comment]
@Lehakos обращаться надо так: tars.flags['custom-flags'] Помогло?

**Comment by Lehakos** [comment]
@artem-malko Всё равно undefined. Вот что показывает `console.log(tars.flags)` http://joxi.ru/Rmzqx1nT0Yp11r

**Comment by Lehakos** [comment]
А вот, что показывает bash http://joxi.ru/KAxzox3hMZ3z0m

**Comment by artem-malko** [comment]
@Lehakos окай, гляну вечерком сегодня

**Comment by artem-malko** [comment]
@Lehakos а попробуй так:
```bash
tars dev -l --custom-flags --backend
```
А потом в js:
```js
tars.flags['--backend']
```

**Comment by Lehakos** [comment]
@artem-malko `undefined`.
Но если запускать так `tars dev -l --custom-flags --backend`, то есть флаг без кавычки, то можно получить флаг через `tars.flags.backend` Правда два флага так передать не получается.

**Comment by artem-malko** [comment]
Кажется для решения этой проблемы необходимо заюзать другой пакет для работы с командной строкой. Буду делать)

**Comment by artem-malko** [comment]
#70
