### ISSUE TITLE
TARS in current project is not compatible with current TARS-CLI!

### ISSUE THREAD

**Issue by kmadorin** [tars/tars-cli#69]
После выхода новой версии tars при работе с tars-cli появляется такая ошибка:
'It seems, that TARS in current project is not compatible with current TARS-CLI!'
'Package "gulp-sass" is not available.'
'Update TARS-CLI via "tars update" and your project via "tars update-project"'

Сделал и tars update и tars update-project. Не помогло

**Comment by artem-malko** [comment]
@kmadorin предлагаю выполнить:
npm un -g tars-cli
npm cache clean
npm i -g tars-cli

**Comment by kmadorin** [comment]
@artem-malko не помогло:

---------------------------------------------------------------------------------
'It seems, that TARS in current project is not compatible with current TARS-CLI!'
'Package "gulp-sass" is not available.'
'Update TARS-CLI via "tars update" and your project via "tars update-project"'
'Please, write to the tars.builder@gmail.com, if update did not help you.'
---------------------------------------------------------------------------------

[11:44:35] 'css:compile-css' errored after 319 ms
[11:44:35] Error: Package gulp-sass is not available.

**Comment by kmadorin** [comment]
@artem-malko переключился на node версии 4.4.7 все заработало

**Comment by Splintex** [comment]
Такая же проблема.
node 6.9.4
npm 4.1.2

**Comment by artem-malko** [comment]
@Splintex попробуйте вариант с новой нодой.

**Comment by Splintex** [comment]
@artem-malko с новой (6.9.5) тоже не работает. Переключился на 4.7.3 - заработало.

**Comment by artem-malko** [comment]
@Splintex необходимо, видимо, руками удалять gulp-sass из глобальных модулей( Какой-то глючный пакет(
