### ISSUE TITLE
Пустой package.json

### ISSUE THREAD

**Issue by Alorian** [tars/tars-cli#75]
Смотрю документацию tars, раздел установка
https://github.com/tars/tars/blob/master/README_RU.md

В качестве рекомендуемого варианта там предлагается использовать tars init. Попробовал поставить через tars init, выполняю следующий шаг установки из документации tars, запускаю gulp init и выдается куча ошибок про отсутствующие модули.

В качестве альтернативного варианта в документации tars предлагается просто скачать проект из гита. Смотрим файл package.json из репозитория
https://github.com/tars/tars/blob/master/package.json
В нем прописано дофига всяких зависимостей, которые через tars cli не прописываются. Вот так выглядит package.json в свежезозданном через tars cli проекте:
```{
  "name": "awesome_project",
  "version": "1.0.0",
  "description": "Your awesome project description",
  "main": "gulpfile.js",
  "directories": {},
  "dependencies": {
    "babel-preset-es2015": "^6.24.1"
  },
  "devDependencies": {
    "gulp": "^3.9.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Это штатное поведение, и после установки через tars cli действительно зависимости нужно прописывать вручную через npm install? Или какая то ошибка?

Ошибка наблюдается в операционной системе windows 10, 
$ npm --version 
5.3.0, 

$ tars --version 
[ TARS ]: TARS-CLI version: "1.9.5"
[ TARS ]: TARS version in current project: "1.9.7"

**Comment by Alorian** [comment]
Похоже что gulp init остался просто по наследству от основного репозитория и реально не используется. Закрываю тикет.

**Comment by artem-malko** [comment]
@Alorian gulp init можно запустить, если локально сами поставите пакеты) Но да, лучше все делать через CLI
