### ISSUE TITLE
Проблема с устновкой

### ISSUE THREAD

**Issue by TIIGRUS** [tars/tars-cli#76]
Помогите , кто может решить проблему с установкой tars-cli. Пробовал и переустанавливать ноде и чистил папки с npm и т.д Ничего не помогает выдает ошибку и не устанавливается. Приложу скрины. 

![part_error_1](https://user-images.githubusercontent.com/11195373/33103408-df1a51ae-cf2a-11e7-950e-5635e0accda7.jpg)

![part_error_2](https://user-images.githubusercontent.com/11195373/33103415-e7d04632-cf2a-11e7-991d-7366dcb1b00b.jpg)

![part_error_3](https://user-images.githubusercontent.com/11195373/33103419-ec4fa108-cf2a-11e7-945b-05c159dc29ee.jpg)

**Comment by TIIGRUS** [comment]
Можно закрывать помогла вот это ссылка. 
https://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm

**Comment by artem-malko** [comment]
О, спасибо)
