### ISSUE TITLE
Не работает установка на последней версии ноды

### ISSUE THREAD

**Issue by Alorian** [tars/tars-cli#77]
Выполняю
$ npm install -g tars-cli
Падает при установке пакета posix. 

Вот если отдельно ставить posix вот такая ошибка:
`PS C:\www> npm i posix

> posix@4.1.1 install C:\www\node_modules\posix
> node-gyp rebuild

> 
> 
> C:\www\node_modules\posix>if not defined npm_config_node_gyp (node "C:\Users\USER\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
> gyp ERR! stack     at C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp ERR! System Windows_NT 10.0.15063
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\www\node_modules\posix
> gyp ERR! node -v v8.9.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open 'C:\www\package.json'
> npm WARN www No description
> npm WARN www No repository field.
> npm WARN www No README data
> npm WARN www No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! posix@4.1.1 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the posix@4.1.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2017-11-27T18_55_16_916Z-debug.log`
> 

Версия ноды
$ node -v
8.9.1

Версия npm
$ npm -v
5.5.1

**Comment by moseevvip** [comment]
Я откатил NPM и смог переустановить TARS, сейчас все заработало.
Сделал:

npm install --global --production windows-build-tools
npm install --global --production npm-windows-upgrade
npm-windows-upgrade --npm-version 4.2.0
npm i -g tars-cli

Сейчас:
Windows 10
$ node -v v8.9.1
$ npm -v 4.2.0

**Comment by alisazhurik** [comment]
Та же фигня! Открыла командную строку пол Админом
Установила 

node.js 8.9.4
npm i -g gulp-cli
npm i -g tars-cli

И все посыпалось. Хэээлп! Работать не могу!

**Comment by artem-malko** [comment]
Завтра будет апдейт) Попробуйте после него

**Comment by artem-malko** [comment]
Fixed in 1.9.8
