### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by Azat74** [tars/tars-cli#83]
Добрый день, скажите пожалуйста, возможно ли сделать так чтобы структура проекта после билда была не склеена и не минифицирована, в папке с файлами css и js сохранялась структура и каждый файл был по отдельности?

**Comment by artem-malko** [comment]
Не совсем понял, файлы должны быть скомпиленными, но лежать также, как и лежали до сборки?
А как быть в случаях, когда один файл ссылается в себе на другой?

Давайте лучше такой вопрос задам: какую задачу вы решаете?

**Comment by Azat74** [comment]
скомпиленные css/js попадают туда же как и в обычном случае, но файлов должно быть много, на каждый файл в режиме разработки свой файл в режиме прода (прогнанный через инструменты автопрефиксер, бабель и т.д.), подключение будет происходить большой портянкой с множеством тегов скрипт, таково требование бекендера, т.к. битрикс сам файлы склеет

**Comment by artem-malko** [comment]
Предлагаю вариант со склейкой js и css с помощью webpack. Тут вы вольны выбирать сами, сколько и какие бандлы у вас появятся. 
Но это уже другой вопрос, на stackoverflow много вариантов того, как это сделать есть.
