### ISSUE TITLE
Обновить webpack

### ISSUE THREAD

**Issue by Yanduz** [tars/tars-cli#84]
npm WARN eslint-loader@2.1.1 requires a peer of webpack@>=2.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
Как я понимаю, eslint-loader не ставится из за того, что плагин webpack'а очень старый, уже 5 версия вышла, а он до сих пор 1.13.2, + много WARN, что плагины сильно устарели или вообще перестали поддерживаться.
(NodeJS 10.11.0, npm 6.4.1, MacOs 10.14)

➜  ~ npm i -g tars-cli
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/tars -> /usr/local/lib/node_modules/tars-cli/bin/tars.js

> fsevents@1.2.4 install /usr/local/lib/node_modules/tars-cli/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/tars-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> phantomjs@1.9.20 install /usr/local/lib/node_modules/tars-cli/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/bt/srcrt1xd7x76qf0wb607d8zc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/tars-cli/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/bt/srcrt1xd7x76qf0wb607d8zc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1537959965245/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/tars-cli/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/tars-cli/node_modules/phantomjs/lib/phantom/bin/phantomjs

> node-sass@4.9.3 install /usr/local/lib/node_modules/tars-cli/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/yan/.npm/node-sass/4.9.3/darwin-x64-64_binding.node

> posix@4.1.2 install /usr/local/lib/node_modules/tars-cli/node_modules/posix
> node-gyp rebuild

  CXX(target) Release/obj.target/posix/src/posix.o
../src/posix.cc:121:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value dir_path(info[0]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:177:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value rlimit_name(info[0]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:217:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value rlimit_name(info[0]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:288:27: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
        String::Utf8Value pwnam(info[0]->ToString());
                          ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:333:27: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
        String::Utf8Value pwnam(info[0]->ToString());
                          ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:373:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value unam(info[0]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:449:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value ident(info[0]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:481:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value message(info[1]->ToString());
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/posix.cc:591:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value str(info[0]);
                      ^
/Users/yan/.node-gyp/10.11.0/include/node/v8.h:2887:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/yan/.node-gyp/10.11.0/include/node/v8config.h:327:29: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
9 warnings generated.
  SOLINK_MODULE(target) Release/posix.node

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/tars-cli/node_modules/spawn-sync
> node postinstall

> node-sass@4.9.3 postinstall /usr/local/lib/node_modules/tars-cli/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/lib/node_modules/tars-cli/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /usr/local/lib/node_modules/tars-cli/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /usr/local/lib/node_modules/tars-cli/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /usr/local/lib/node_modules/tars-cli/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
npm WARN eslint-loader@2.1.1 requires a peer of webpack@>=2.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.

+ tars-cli@1.9.8
added 1750 packages from 920 contributors in 51.995s
➜  ~

**Comment by artem-malko** [comment]
Спасибо за issue. Понимаю, постараюсь сделать( Времени катастрофически мало(

**Comment by artem-malko** [comment]
done
