### ISSUE TITLE
Need fix npm cache clean error

### ISSUE THREAD

**Issue by donbot-inc** [tars/tars-cli#86]
What is `npm cache clean` command used for? For check what everything is consistent or reclaiming disk space? In the first case, need use `npm cache verify` command and `npm cache clean` for npm version lower then 5. In second case need use `npm cache clean --force` instead.

Reference:
https://github.com/tars/tars/issues/360
https://github.com/tars/tars/issues/361

**Comment by artem-malko** [comment]
done, as I think)
