### ISSUE TITLE
Include semver package for compare tars versions

### ISSUE THREAD

**Issue by donbot-inc** [tars/tars-cli#88]
Version `'1.5.0' > '1.10.0'` in JS, LOOOL. Maybe include [semver](https://www.npmjs.com/package/semver) package for compare tars versions?

**Comment by artem-malko** [comment]
I agree! Could you make a pull request? I think, it is ok to make one request for #87 and #88 too.

**Comment by donbot-inc** [comment]
> I agree! Could you make a pull request? I think, it is ok to make one request for #87 and #88 too.
Ok, send soon.
