### ISSUE TITLE
flatmap-stream удален из npm 

### ISSUE THREAD

**Issue by pinkman-frontend-user** [tars/tars-cli#92]
Пакет удалили из npm, как небезопасный и теперь ничего не ставится

![image](https://user-images.githubusercontent.com/44676144/49033773-1bab6680-f1c1-11e8-8bb2-1b93c45baffe.png)

https://github.com/hugeglass/flatmap-stream/issues/2

**Comment by artem-malko** [comment]
tars-cli не ставится? Какая ОС и версия ноды?

**Comment by artem-malko** [comment]
@pinkman-frontend-user ↑↑↑

**Comment by pinkman-frontend-user** [comment]
tars-cli, последний
node восьмая, 
Чья это зависимость, я с ходу не понял. 
Пытался развернуть на маке и в центоси, результат на скрине

с обновлением на 1.10 было всё ок. Ошибка свежая

**Comment by pinkman-frontend-user** [comment]
![image](https://user-images.githubusercontent.com/44676144/49059994-ae2d2380-f21c-11e8-9ee2-df4f3440f9c5.png)
вот она, нашлось

**Comment by artem-malko** [comment]
Не, я про то, что tars-cli ставится или нет? Это зависимости двух пакетов для мемоизации pug и jade. Придется форки делать скорее всего( Постараюсь как можно быстрее.

**Comment by pinkman-frontend-user** [comment]
у меня докер образ есть, поэтому живем, а с нуля не ставится.

**Comment by pinkman-frontend-user** [comment]
массовая проблема, даже в новостях пишут https://tproger.ru/news/event-stream-backdoor/

**Comment by artem-malko** [comment]
Да, про проблему в курсе) Работаем)

**Comment by artem-malko** [comment]
Done!
