### ISSUE TITLE
Не могу установить

### ISSUE THREAD

**Issue by NabAlexey** [tars/tars-cli#94]
Сейчас я поставил win10 с нуля, поставил дрова, и сразу же node 10,
далее пытаюсь установить, ругается на python, 
ставлю питон вместе со всем остальным(https://www.npmjs.com/package/windows-build-tools#examples-of-modules-supported (отдельно питон тоже пробовал ставить))
Далее выводит ошибку
![image](https://user-images.githubusercontent.com/21338809/49684333-e1589800-fae3-11e8-957b-1b8f329c4622.png)
Уже её поправить никак не могу

**Comment by NabAlexey** [comment]
node довнгрейдил до 7, npm до 4.6.1
Все таже ошибка. Наверно можно сделать вывод что это из за последней обновы windows 10?

**Comment by NabAlexey** [comment]
![image](https://user-images.githubusercontent.com/21338809/49685061-f9cdb000-faed-11e8-932d-0eff45cb195c.png)

**Comment by artem-malko** [comment]
На самом деле все установилось. Самая последняя строка на это указывает — updated 1 package. tars -v же выдает результат.

Ошибки из-за того, что не может быть установлена опциональная зависимость.

**Comment by NabAlexey** [comment]
В 
node 11.4 - не работает,
node 10.14.1 - не работает,
node 9.6.0  - работает

**Comment by artem-malko** [comment]
@NabAlexey А какая версия Windows? Просто у нас тесты на на винде в целом гоняются, но не на 10-ке.

**Comment by NabAlexey** [comment]
@artem-malko Windows 10, последние обновы

**Comment by CcRaZyY** [comment]
У меня 2 компа с последней виндой 10) бывают зависания при попытки отключить какую-то команду, но при инициализации не было

**Comment by NabAlexey** [comment]
@CcRaZyY Точную версию, редакцию винды, версию ноды в студию

**Comment by CcRaZyY** [comment]
На выходных менял  ssd) так что у меня установка с нуля была, до этого на обновлениях работал ещё с бета версий..

**Comment by NabAlexey** [comment]
@ Редакция? Установщик свежий скачивал?

**Comment by tahavn** [comment]
А решение то какое? столкнулся с такой же проблемой, зависает при http://joxi.ru/v29oOoVcZjGd5r на windows 10

**Comment by NabAlexey** [comment]
> А решение не было найдено? только подбирать версии node и npm? столкнулся с такой же проблемой, зависает при http://joxi.ru/v29oOoVcZjGd5r на windows 10

Ставь 9 ноду
